export const TRIVIA_DATA_REQUESTED = 'TRIVIA_DATA_REQUESTED';
export const TRIVIA_DATA_LOADED = 'TRIVIA_DATA_LOADED';
export const TRIVIA_API_ERROR = 'TRIVIA_API_ERROR';

export const UPDATE_TRIVIA_VIEW = 'UPDATE_TRIVIA_VIEW';

export const SET_SELECTED_ANSWER = 'SET_SELECTED_ANSWER';

export const INCREMET_CURRENT_TRIVIA_INDEX = 'INCREAMET_TRIVIA_INDEX_COUNT';
export const DECREMET_CURRENT_TRIVIA_INDEX = 'DECREAMET_TRIVIA_INDEX_COUNT';

