export const TRIVIA_DATA_REQUESTED = 'TRIVIA_DATA_REQUESTED';
export const TRIVIA_DATA_LOADED = 'TRIVIA_DATA_LOADED';
export const TRIVIA_API_ERROR = 'TRIVIA_API_ERROR';

export const UPDATE_TRIVIA_VIEW = 'UPDATE_TRIVIA_VIEW';

export const SET_SELECTED_ANSWER = 'SET_SELECTED_ANSWER';

export const INCREMET_CURRENT_TRIVIA_INDEX = 'INCREMET_CURRENT_TRIVIA_INDEX';
export const DECREMET_CURRENT_TRIVIA_INDEX = 'DECREMET_CURRENT_TRIVIA_INDEX';

export const SET_TOTAL_SCORE = 'SET_TOTAL_SCORE';


