export const TRIVIA_DATA_REQUESTED = 'TRIVIA_DATA_REQUESTED';
export const TRIVIA_DATA_LOADED = 'TRIVIA_DATA_LOADED';
export const TRIVIA_API_ERROR = 'TRIVIA_API_ERROR';

export const UPDATE_TRIVIA_VIEW = 'UPDATE_TRIVIA_VIEW';

export const SET_SELECTED_ANSWER = 'SET_SELECTED_ANSWER';

